### ISSUE TITLE
Running an interaction with an interface filter can raise an error

### ISSUE THREAD

**Issue by tfausak** [orgsync/active_interaction#263]
I was surprised to discover that running an interaction (via `.run`) with an interface filter can blow up. 

``` rb
class InterfaceInteraction < ActiveInteraction::Base
  interface :an_interface

  def execute
    inputs
  end
end

InterfaceInteraction.run(interface: nil)
# ActiveInteraction::NoDefaultError: an_interface
```

That's not what I expected. Other filters behave as expected.

``` rb
class BooleanInteraction < ActiveInteraction::Base
  boolean :a_boolean

  def execute
    inputs
  end
end

BooleanInteraction.run(a_boolean: nil)
# => #<BooleanInteraction:0x...>
```

**Comment by tfausak** [comment]
Here's a stack trace:

```
from .../lib/active_interaction/filter.rb:124:in `default'
from .../lib/active_interaction/filter.rb:101:in `clean'
from .../lib/active_interaction/base.rb:242:in `block in populate_filters'
from .../lib/active_interaction/base.rb:240:in `each'
from .../lib/active_interaction/base.rb:240:in `populate_filters'
from .../lib/active_interaction/base.rb:232:in `process_inputs'
from .../lib/active_interaction/base.rb:182:in `initialize'
from .../lib/active_interaction/concerns/runnable.rb:118:in `new'
from .../lib/active_interaction/concerns/runnable.rb:118:in `new'
from .../lib/active_interaction/concerns/runnable.rb:132:in `run'
```

**Comment by tfausak** [comment]
This also affects model filters. 

``` rb
Class.new(ActiveInteraction::Base) { model :object }.run
# ActiveInteraction::NoDefaultError: object
```

**Comment by tfausak** [comment]
This happens because `nil` passes the interface and model checks. That means `#cast` returns `nil` instead of calling `super`. Calling `super` would raise a `MissingValueError`, which `#populate_filters` would catch. 

I feel weird about this case. If `nil` is an acceptable value for your interface or model filter, you'd have to set `default: nil` to actually accept it. 

``` rb
Class.new(ActiveInteraction::Base) { interface :anything, default: nil }.run
# NotImplementedError: NotImplementedError
Class.new(ActiveInteraction::Base) { model :object, default: nil }.run
# NotImplementedError: NotImplementedError
```
