### ISSUE TITLE
Errors#merge! breaks with autosave associations

### ISSUE THREAD

**Issue by Odaeus** [orgsync/active_interaction#419]
Hi,

I have a `Post` object that `has_one :schedule` with `accepts_nested_attributes_for :schedule` as well. The latter method sets `autosave: true`, which unfortunately has the effect of hoisting up errors into the parent object so that the errors object on Post looks like this:

```
(byebug) post.errors.details
{:"schedule.publish_at"=>[{:error=>:blank}]}
```

The naughty pseudo-attribute name with the dot in it breaks Active Interaction's `errors.merge!(post.errors)`, resulting in the stracktrace below.

Any idea on the best way to resolve this if I want to keep autosave enabled?

```
Failure/Error: errors.merge!(post.errors)

NoMethodError:
  super: no superclass method `schedule.publish_at' for #<Post:0x0055bcbe0fe058>
  Did you mean?  scheduled_for_publication?
  Did you mean?  scheduled_for_publication?
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activemodel-5.0.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/enumerize-2.1.2/lib/enumerize/base.rb:61:in `read_attribute_for_validation'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activemodel-5.0.3/lib/active_model/errors.rb:494:in `generate_message'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_interaction-3.5.2/lib/active_interaction/errors.rb:145:in `translate'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_interaction-3.5.2/lib/active_interaction/errors.rb:132:in `merge_detail!'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_interaction-3.5.2/lib/active_interaction/errors.rb:123:in `block (2 levels) in merge_details!'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_interaction-3.5.2/lib/active_interaction/errors.rb:119:in `each'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_interaction-3.5.2/lib/active_interaction/errors.rb:119:in `block in merge_details!'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_interaction-3.5.2/lib/active_interaction/errors.rb:118:in `each'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_interaction-3.5.2/lib/active_interaction/errors.rb:118:in `merge_details!'
# /home/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active_interaction-3.5.2/lib/active_interaction/errors.rb:95:in `merge!'
# ./app/interactions/admin/posts/create.rb:33:in `execute'
```

**Comment by AaronLasseigne** [comment]
Based on the stack trace it looks like the issue is coming from `generate_message` inside of ActiveModel. I tried it on a local Rails app I have and `generate_message` failed to properly handle the nested error. I think this might be an issue for Rails.

**Comment by Odaeus** [comment]
That is a good point. The Rails side doesn't support any handling of these nested attribute names in the error yet it generates them from somewhere. I'll have a look further at the Rails side but won't realistically be able to until September, so I'll close this ticket for now. Thanks!

**Comment by ninjarails** [comment]
I had to use something like this:
```
      occupancy.errors.messages.each do |column, messages|
          messages.each { |m| errors.add(column, m) }
      end
```
